logging:
  level:
    org:
      springframework: ERROR
    root: ERROR
spring:
  data:
    mongodb:
      database: customerdb
      port: '27017'
      host: localhost
  application:
    name: CustomerService
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      group-id: gid
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    bootstrap-servers: localhost:9092
  zipkin:
    base-url: http://localhost:9411/
  logging:
    file=C:/elk/spring-boot-elk.log
sleuth:
  sampler:
    probability: 1 #100% (default = 10%)

app:
  topic:
    customerchangetopic: customerchangetopic

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8761/eureka/ ,
                   http://eurekaserver2:8762/eureka/
